version: '2'

services:

  jira:
    container_name: jira
    build: jira/docker/.
    ports:
      - 8080:8080
    networks:
      - jiranet
    environment:
      JRE_HOME: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/

  mysql:
    container_name: mysql
    build: mysql/docker/.
    command: --init-file=/setup.sql
    ports:
      - 3306:3306
    networks:
      - jiranet
    environment:
      MYSQL_ROOT_PASSWORD: password

#  backup:
#    container_name: backup

networks:
  jiranet:
    external:
      name: jiranet




